[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
