name: Rust

on:
  push:
    branches: [ "main" ]
    tags: v*
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cli

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:

    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./cli

    steps:
    - uses: actions/checkout@v4
    - run: cargo build --release
    - run: mv target/release/cli target/release/aibranch
    - run: gh release create ${{ github.ref_name }} --generate-notes ./target/release/aibranch#aibranch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
